### ISSUE TITLE
app在安卓11打开出现问题

### ISSUE THREAD

**Issue by Ningzetao** [hyqs/HttpDownload#1]
线程拉到100后点击开始测速会暂停

**Comment by hyqs** [comment]
emmp。。。，直接拉100，服务器会反应不过来，就像一个说话快的人一连说一百个字，你能记住几个？



---原始邮件---
发件人: "Ningzetao"<notifications@github.com&gt;
发送时间: 2021年3月1日(周一) 下午3:53
收件人: "hyqs/HttpDownload"<HttpDownload@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hyqs/HttpDownload] app在安卓11打开出现问题 (#1)




 
线程拉到100后点击开始测速会暂停

**Comment by Ningzetao** [comment]
这个APP原理是什么，没用请求存储权限但是又能消耗我的流量

**Comment by hyqs** [comment]
对牛弹琴，源码都给了，看不懂就算了
